name = "token-sprint"
compatibility_date = "2024-03-20"

[build]
command = "next build"
cwd = "."

[assets]
directory = ".next/static"
not_found_handling = "single-page-application"

[site]
bucket = ".next/static"

[env.production]
name = "token-sprint-prod"

[env.staging]
name = "token-sprint-staging" 